### ISSUE TITLE
Improve execute_add_reward_balance

### ISSUE THREAD

**Issue by peara** [halotrade-zone/halo-farm#7]
Some issues:
- need to check if `new_start_time` is greater than last phase's `end_time`
- no need to validate `reward_token`, it should be validated when instantiate only once
- rename `pool_info` to `phase_info`: https://github.com/halotrade-zone/halo-farm/blob/main/contracts/halo-farm/src/contract.rs#L134 
- `asset` is of type `RewardTokenAsset` but only require `amount`. Need to validate or cleanup
- if a phase has been activated, do not allow to add reward

**Comment by peara** [comment]
@haitranwang @hoanm

**Comment by haitranwang** [comment]
Hi a @peara 
- need to check if new_start_time is greater than last phase's end_time -> Fixed
- no need to validate reward_token, it should be validated when instantiate only once -> I removed `RewardTokenAsset` struct
- rename pool_info to phase_info: https://github.com/halotrade-zone/halo-farm/blob/main/contracts/halo-farm/src/contract.rs#L134 -> Fixed
- asset is of type RewardTokenAsset but only require amount. Need to validate or cleanup -> I removed `RewardTokenAsset` struct
- if a phase has been activated, do not allow to add reward -> Added a check
Please help me review again. Thank you
